name = "flares3"
main = "src/index.ts"
compatibility_date = "2024-09-01"
node_compat = true

[assets]
directory = "../frontend/dist"
binding = "ASSETS"

[vars]
MAX_FILE_SIZE = "5368709120"
TOTAL_STORAGE = "10737418240"

[[d1_databases]]
binding = "DB"
database_name = "flares3-r2"
database_id = "REPLACE_WITH_D1_ID"

[[triggers.crons]]
cron = "0 * * * *"
